/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import communication.KomunikacijaSaServerom;
import domen.Obaveza;
import domen.Racun;
import domen.Rata;
import java.util.ArrayList;
import java.util.Calendar;
//import java.util.Date;
//import java.sql.Date;
import javax.swing.JOptionPane;
import konstante.Konstante;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Ookee
 */
public class NovaObavezaForm extends javax.swing.JFrame {

    private Racun racun;
    private RacunForm rf;

    /**
     * Creates new form NoviKorisnikForm
     */
    public NovaObavezaForm(Racun racun, RacunForm rf) {
        initComponents();
        this.racun = racun;
        this.rf = rf;
        popuniCmbBrojRata();
        azurirajLabele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImePrezime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIznos = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        cmbBrojRata = new javax.swing.JComboBox();
        lblRacun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImePrezime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblImePrezime.setText("Ime Prezime");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Iznos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Broj rata");

        txtIznos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIznosActionPerformed(evt);
            }
        });

        btnSacuvaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        cmbBrojRata.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblRacun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRacun.setText("Racun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImePrezime)
                            .addComponent(lblRacun))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBrojRata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIznos, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblImePrezime)
                .addGap(18, 18, 18)
                .addComponent(lblRacun)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbBrojRata, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIznosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIznosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIznosActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        double iznos;
        try {
            iznos = Double.parseDouble(txtIznos.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Molim Vas unesite samo brojeve u iznos.");
            return;
        }
        int brojRata = Integer.parseInt(cmbBrojRata.getSelectedItem().toString().substring(0, cmbBrojRata.getSelectedItem().toString().indexOf(" ")));
        Obaveza o = new Obaveza(0, iznos, new java.util.Date(), racun);
        ArrayList<Rata> listaRata = new ArrayList<>();
        for (int i = 0; i < brojRata; i++) {
            Rata r = new Rata(0, o, (iznos / brojRata), (addMonth(new java.util.Date(), i + 1)));
            listaRata.add(r);
        }
        // posalji obavezu
        KlijentskiZahtev kz = new KlijentskiZahtev();
        ArrayList<Object> listaObj = new ArrayList<>();
        listaObj.add(o);
        listaObj.add(listaRata);
        kz.setOperacija(Konstante.KREIRAJ_NOVU_OBAVEZU);
        kz.setParametar(listaObj);
        ServerskiOdgovor so;
        try {
            KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
            so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom povezivanja.");
            return;
        }
        if (so.getPoruka().equals("1")) {
            JOptionPane.showMessageDialog(this, "Kreirana je nova obaveza za dati račun.");
            rf.osveziObaveze();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Nije mogućre kreirati obavezu za dati račun.");
        }

        // posalji rate
        /*KlijentskiZahtev kz1 = new KlijentskiZahtev();
        kz1.setOperacija(Konstante.KREIRAJ_RATE);
        kz1.setParametar(listaRata);
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz1);
        ServerskiOdgovor so1 = KomunikacijaSaServerom.getInstance().primiOdgovor();
        if(so1.getPoruka().equals("0")){
            JOptionPane.showMessageDialog(this, "Nije mogućre kreirati obavezu za dati račun.");
            return;
        }*/
        // dodaj obavezu u listu
        // dodaj rate u listu

    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbBrojRata;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImePrezime;
    private javax.swing.JLabel lblRacun;
    private javax.swing.JTextField txtIznos;
    // End of variables declaration//GEN-END:variables

    private void popuniCmbBrojRata() {
        cmbBrojRata.removeAllItems();
        cmbBrojRata.addItem("3 rate");
        cmbBrojRata.addItem("6 rata");
        cmbBrojRata.addItem("12 rata");
    }

    public static java.sql.Date addMonth(java.util.Date date, int i) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.add(Calendar.MONTH, i);
        java.sql.Date date1 = new java.sql.Date((cal.getTime()).getTime());
        System.out.println("Datum je " + date1);
        return date1;
    }

    private void azurirajLabele() {
        lblImePrezime.setText(racun.getObveznik().getIme() + " " + racun.getObveznik().getPrezime());
        lblRacun.setText(racun.getRacun().getNaziv());
    }
}
