/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import communication.KomunikacijaSaServerom;
import domen.Obveznik;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import konstante.Konstante;
import models.ModelTabeleObveznik;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Ookee
 */
public class PoreskiObvezniciForm extends javax.swing.JFrame {

    ModelTabeleObveznik mto = new ModelTabeleObveznik();

    /**
     * Creates new form PoreskiObvezniciForm
     */
    public PoreskiObvezniciForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        srediTabeluObveznika();
        ucitajPoreskeObveznike();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtObveznik = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblObveznici = new javax.swing.JTable();
        btnStanje = new javax.swing.JButton();
        btnNoviObveznik = new javax.swing.JButton();
        btnObrisiObveznika = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblObveznici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblObveznici);

        btnStanje.setText("Stanje");
        btnStanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStanjeActionPerformed(evt);
            }
        });

        btnNoviObveznik.setText("Dodaj novog obveznika");
        btnNoviObveznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviObveznikActionPerformed(evt);
            }
        });

        btnObrisiObveznika.setText("Obriši obveznika");
        btnObrisiObveznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiObveznikaActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNoviObveznik, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisiObveznika, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 272, Short.MAX_VALUE))
                            .addComponent(txtObveznik))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtObveznik)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStanje)
                    .addComponent(btnNoviObveznik)
                    .addComponent(btnObrisiObveznika))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoviObveznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviObveznikActionPerformed
        JFrame forma = new NoviObveznikForm(this);
        forma.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        forma.setLocationRelativeTo(null);
        forma.setVisible(true);
    }//GEN-LAST:event_btnNoviObveznikActionPerformed

    private void btnStanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStanjeActionPerformed
        int brObveznika = tblObveznici.getSelectedRow();
        if (brObveznika < 0) {
            JOptionPane.showMessageDialog(this, "Obeležite obveznika čije stanje želite da pregledate.");
            return;
        }
        JFrame forma = new RacunForm(mto.getListaObveznika().get(brObveznika).getBrObveznika());
        forma.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        forma.setLocationRelativeTo(null);
        forma.setVisible(true);
    }//GEN-LAST:event_btnStanjeActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Konstante.NADJI_OBVEZNIKA);
        Obveznik o = new Obveznik(0, txtObveznik.getText().trim(), txtObveznik.getText().trim(), null, null);
        kz.setParametar(o);
        ServerskiOdgovor so;
        try {
            KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
            so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom povezivanja.");
            return;
        }
        ArrayList<Obveznik> listaObveznika = (ArrayList<Obveznik>) so.getOdogovor();
        mto.setListaObveznika(listaObveznika);
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnObrisiObveznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiObveznikaActionPerformed
        int brObveznika = tblObveznici.getSelectedRow();
        if (brObveznika < 1) {
            JOptionPane.showMessageDialog(this, "Obeležite obveznika kojeg želite da obrišete.");
            return;
        }
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Konstante.OBRISI_OBVEZNIKA);
        kz.setParametar(mto.getListaObveznika().get(brObveznika));
        ServerskiOdgovor so;
        try {
            KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
            so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom povezivanja.");
            return;
        }
        if (so.getPoruka().equals("1")) {
            JOptionPane.showMessageDialog(this, "Obveznik je uspešno obrisan.");
            osveziTabelu();
        } else {
            JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom brisanja obveznika.");
        }
    }//GEN-LAST:event_btnObrisiObveznikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoreskiObvezniciForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoreskiObvezniciForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoreskiObvezniciForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoreskiObvezniciForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoreskiObvezniciForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoviObveznik;
    private javax.swing.JButton btnObrisiObveznika;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnStanje;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblObveznici;
    private javax.swing.JTextField txtObveznik;
    // End of variables declaration//GEN-END:variables

    private void ucitajPoreskeObveznike() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Konstante.VRATI_SVE_OBVEZNIKE);
        ServerskiOdgovor so;
        try {
            KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
            so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom povezivanja.");
            return;
        }
        ArrayList<Obveznik> listaPoreskihObveznika = (ArrayList<Obveznik>) so.getOdogovor();
        mto.setListaObveznika(listaPoreskihObveznika);
    }

    private void srediTabeluObveznika() {
        mto = new ModelTabeleObveznik();
        tblObveznici.setModel(mto);
    }

    public void osveziTabelu() {
        ucitajPoreskeObveznike();
    }

}
