/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import communication.KomunikacijaSaServerom;
import domen.Racun;
import domen.Transakcija;
import java.util.Date;
import javax.swing.JOptionPane;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Ookee
 */
public class UplataForm extends javax.swing.JFrame {

    private Racun racun;
    private RacunForm rf;

    /**
     * Creates new form UplataForm
     */
    public UplataForm(Racun racun, RacunForm rf) {
        initComponents();
        this.racun = racun;
        this.rf = rf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIznos = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Iznos");

        txtIznos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIznosActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Uplati");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtIznos, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIznos)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIznosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIznosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIznosActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        double iznos;
        String opis = "Uplata na račun '" + racun.getRacun().getNaziv() + "'";
        try {
            iznos = Double.parseDouble(txtIznos.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Molim Vas unesite samo brojeve u iznos.");
            return;
        }
        Transakcija t = new Transakcija(0, iznos, new Date(), opis, racun);
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(konstante.Konstante.UPLATA_PRETPLATE);
        kz.setParametar(t);
        ServerskiOdgovor so;
        try {
            KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
            so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom povezivanja.");
            return;
        }
        if (so.getPoruka().equals("1")) {
            rf.setLabelStanje(iznos);
            rf.azurirajStanje();
            JOptionPane.showMessageDialog(this, "Uplata je uspešno izvršena.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Došlo je do greke prilikom uplate.");
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIznos;
    // End of variables declaration//GEN-END:variables
}
